name: Build and deploy ASP.Net Core app to Azure Web App - GeocitiesTimes

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      # 1) Node for Angular build
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install client deps
        working-directory: geocitiestimes.client     # <-- adjust if your client dir is different
        run: npm ci

      - name: Build Angular (prod to wwwroot)
        working-directory: geocitiestimes.client
        run: npm run build -- --configuration production
        # Make sure this configuration's outputPath points to ../GeocitiesTimes.Server/wwwroot

      # 2) .NET
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'                      # Use 9.x if you target net9.0

      - name: Restore
        run: dotnet restore

      - name: Build with dotnet
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: dotnet publish
        run: dotnet publish GeocitiesTimes.Server/GeocitiesTimes.Server.csproj -c Release -o "${{env.DOTNET_ROOT}}/myapp" --no-build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E71BC74E4F974FBFA1C533671993B6AA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3B1199DB309A4E36978639D534048D86 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0E469FD7DE74412E9E07905404DEF95C }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'GeocitiesTimes'
          slot-name: 'Production'
          package: .
